name: b350_lab

include:
  - dashboard/dashboard.compose.yaml
  - frigate/bio-frigate.compose.yaml

services:
  #####################
  # WEI Core Services #
  #####################
  b350_wc_server:
    image: ghcr.io/ad-sdl/wei
    container_name: b350_wc_server
    ports:
      - 8000:8000
    volumes:
      - .:/workcell_defs
      - ~/.wei:/home/app/.wei
      - diaspora_config:/home/app/.diaspora
    command: python3 -m wei.server --workcell /workcell_defs/b350_workcell.yaml --use_diaspora false
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=1000
      - GROUP_ID=1000
    depends_on:
      - b350_redis
  b350_wc_engine:
    image: ghcr.io/ad-sdl/wei
    container_name: b350_wc_engine
    volumes:
      - .:/workcell_defs
      - ~/.wei:/home/app/.wei
    command: python3 -m wei.engine --workcell /workcell_defs/b350_workcell.yaml --use_diaspora false
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=1000
      - GROUP_ID=1000
    depends_on:
      - b350_redis
  b350_redis:
    image: redis
    container_name: b350_redis
    ports:
      - 6379:6379
    volumes:
      - ~/.wei/redis:/data
    command: redis-server --save 60 1 --loglevel warning

  ###############
  # WEI Modules #
  ###############

  platecrane_node:
    image: ghcr.io/ad-sdl/hudson_platecrane_module
    container_name: platecrane_node
    ports:
      - 2000:2000
    command: python3 -m platecrane_rest_node --port=2000 --device='/dev/ttyUSB2'
    privileged: true
    volumes:
      - /dev:/dev

  brooks_xpeel_node:
    image: ghcr.io/ad-sdl/brooks_xpeel_module
    container_name: brooks_xpeel_node
    ports:
      - 2001:2001
    command: python -m brooks_xpeel_rest_node --port=2001 --device='/dev/ttyUSB4'
    privileged: true
    volumes:
      - /dev:/dev

  a4s_sealer_node:
    image: ghcr.io/ad-sdl/a4s_sealer_module
    container_name: a4s_sealer_node
    ports:
      - 2002:2002
    command: python -m a4s_sealer_rest_node --port=2002 --device='/dev/ttyUSB6'
    privileged: true
    volumes:
      - /dev:/dev

  liconic_node:
    image: ghcr.io/ad-sdl/liconic_module
    container_name: liconic_node
    ports:
      - 2003:2003
    command: python liconic_module/scripts/liconic_rest_node.py --port=2003 --device='/dev/ttyUSB0'
    privileged: true
    volumes:
      - /dev:/dev

################
# Data Storage #
################
volumes:
  diaspora_config:
    driver: local
