name: b350_lab

services:
  # Single Redis used by whole lab
  b350_redis:
    image: redis
    container_name: b350_redis
    ports:
      - 6379:6379
    volumes:
      - ~/.wei/redis:/data
    command: redis-server --save 60 1 --loglevel warning

  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:b350_redis:6379
    depends_on:
      - b350_redis

  platecrane_node:
    image: ghcr.io/ad-sdl/hudson_platecrane_module
    container_name: platecrane_node
    ports:
      - 2000:2000
    command: python3 hudson_platecrane_module/src/platecrane_rest_node.py --port=2000
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    privileged: true
    volumes:
      - /dev:/dev

  brooks_xpeel_node:
    image: ghcr.io/ad-sdl/brooks_xpeel_module
    container_name: brooks_xpeel_node
    ports:
      - 2001:2001
    command: python brooks_xpeel_module/scripts/brooks_xpeel_rest_node.py --port=2001
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    privileged: true
    volumes:
      - /dev:/dev

  a4s_sealer_node:
    image: ghcr.io/ad-sdl/a4s_sealer_module
    container_name: a4s_sealer_node
    ports:
      - 2002:2002
    command: python a4s_sealer_module/scripts/a4s_sealer_rest_node.py --port=2002
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    privileged: true
    volumes:
      - /dev:/dev

  # liconic_node:
  #   image: ghcr.io/ad-sdl/liconic_module
  #   container_name: liconic_node
  #   ports:
  #     - 2002:2002
  #   command: python liconic_module/scripts/liconic_rest_node.py --port=2003
  #   environment:
  #     - USER_ID=1000
  #     - GROUP_ID=1000
  #   privileged: true
  #   volumes:
  #     - /dev:/dev

################
# Data Storage #
################
volumes:
  diaspora_config:
    driver: local
